
package Formularios;

import clases.Pedidos;
import clases.Presentacion;
import clases.Productos;
import clases.Proveedores;
import clases.Tipos;
import java.awt.Dimension;
import java.awt.Image;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

public class FrmAgregarPedido extends javax.swing.JFrame {
   //Modelos
    DefaultTableModel listado= new DefaultTableModel();
    DefaultComboBoxModel cbidproveedores=new DefaultComboBoxModel();
    DefaultComboBoxModel cbproveedores=new DefaultComboBoxModel();
    DefaultComboBoxModel cbidtipos=new DefaultComboBoxModel();
    DefaultComboBoxModel cbtipos=new DefaultComboBoxModel();
    DefaultComboBoxModel cbidProductos=new DefaultComboBoxModel();
    DefaultComboBoxModel cbProductos=new DefaultComboBoxModel();
    DefaultComboBoxModel cbidPresentaciones=new DefaultComboBoxModel();
    DefaultComboBoxModel cbPresentaciones=new DefaultComboBoxModel();
    DateFormat calendario= DateFormat.getDateInstance();
    
    //Imagenes
    ImageIcon fondo = new ImageIcon(getClass().getResource("/iconos/fondo2.jpg"));
    ImageIcon  fond;
    
    //Llamados
    FrmNuevoProveedor CargarNuevoProveedor= new FrmNuevoProveedor();
    Proveedores proveedor=new Proveedores();
    Tipos tipo= new Tipos();
    Productos producto= new Productos();
    Presentacion presentacion= new Presentacion();
    Pedidos pedido= new Pedidos();
    
    //ResultSet
    ResultSet rstProveedores=null;
    ResultSet rstTipos=null;
    ResultSet rstTiposDependeProducto=null;
    ResultSet rstProductos=null;
    ResultSet rstPresentaciones=null;
    
    public FrmAgregarPedido() {
        initComponents();
        //Configuraciones
        Calendar hoy = new GregorianCalendar();
        fecha.setCalendar(hoy);
        this.setSize(new Dimension(540, 625));
        this.fond = new ImageIcon(fondo.getImage().getScaledInstance(lblfondo.getWidth(), lblfondo.getHeight(), Image.SCALE_DEFAULT));
        lblfondo.setIcon(fond);
        //Combo box
        llenarProveedores();
        llenarTipo();
        llenarProducto();
    }
    public void llenarProveedores(){
       rstProveedores=proveedor.llenarProveedores();
         try {
            while (rstProveedores.next()){
                cbidproveedores.addElement(rstProveedores.getInt(1));
                cbproveedores.addElement(rstProveedores.getString(2));
                
            } cmbProveedores.setModel(cbproveedores);
        } catch (SQLException ex) {
            Logger.getLogger(FrmAgregarPedido.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void llenarTipo(){
       rstTipos= tipo.llenarTipos();
        try {
            while(rstTipos.next()){
                cbidtipos.addElement(rstTipos.getInt(1));
                cbtipos.addElement(rstTipos.getString(2));
                
            }cmbTipos.setModel(cbtipos);
        } catch (SQLException ex) {
            Logger.getLogger(FrmAgregarPedido.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void llenarProducto(){
     rstProductos= producto.llenarProductos();
        try {
            while(rstProductos.next()){
                cbidProductos.addElement(rstProductos.getInt(1));
                cbProductos.addElement(rstProductos.getString(3));
            } cmbProductos.setModel(cbProductos);
        } catch (SQLException ex) {
            Logger.getLogger(FrmAgregarPedido.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void llenarPresentacion(){
        
    }
    
    public void CualPedido(){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        btnAgregarALista = new javax.swing.JButton();
        lblinfoNuevoPedido = new javax.swing.JLabel();
        lblinfoNumero = new javax.swing.JLabel();
        lblNumero = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblinfoproveedor = new javax.swing.JLabel();
        cmbProveedores = new javax.swing.JComboBox<>();
        btnNuevoProveedor = new javax.swing.JButton();
        lblinfoproductos = new javax.swing.JLabel();
        cmbTipos = new javax.swing.JComboBox<>();
        lblinfocategoria = new javax.swing.JLabel();
        lblInfoProducto = new javax.swing.JLabel();
        cmbProductos = new javax.swing.JComboBox<>();
        cmbPresentaciones = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnGuardarPedido = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        fecha = new com.toedter.calendar.JDateChooser();
        lblfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblProductos.setBackground(new java.awt.Color(153, 255, 153));
        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblProductos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 512, 232));

        btnAgregarALista.setText("Agregar a la lista");
        getContentPane().add(btnAgregarALista, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 146, 34));

        lblinfoNuevoPedido.setText("Nuevo pedido:");
        getContentPane().add(lblinfoNuevoPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 11, 128, 26));

        lblinfoNumero.setText("Numero de pedido:");
        getContentPane().add(lblinfoNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 11, -1, -1));
        getContentPane().add(lblNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 11, 172, 26));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 550, 10));

        lblinfoproveedor.setText("Elija un Proveedor: ");
        getContentPane().add(lblinfoproveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 120, -1));

        getContentPane().add(cmbProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 200, -1));

        btnNuevoProveedor.setText("Nuevo Proveedor");
        btnNuevoProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoProveedorActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevoProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 160, -1));

        lblinfoproductos.setText("Elija los productos:");
        getContentPane().add(lblinfoproductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 150, -1));

        getContentPane().add(cmbTipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 160, 30));

        lblinfocategoria.setText("Elegir por categoria:");
        getContentPane().add(lblinfocategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 140, -1));

        lblInfoProducto.setText("Elija el producto:");
        getContentPane().add(lblInfoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 200, -1));

        getContentPane().add(cmbProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 270, 30));

        getContentPane().add(cmbPresentaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 270, 30));

        jLabel1.setText("Presentacion:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 120, -1));

        btnGuardarPedido.setText("Guardar Pedido");
        getContentPane().add(btnGuardarPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 540, 190, 40));

        jLabel2.setText("Fecha:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 50, -1));

        getContentPane().add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 130, -1));
        getContentPane().add(lblfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoProveedorActionPerformed
        CargarNuevoProveedor.setVisible(true);
    }//GEN-LAST:event_btnNuevoProveedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAgregarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAgregarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAgregarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAgregarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAgregarPedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarALista;
    private javax.swing.JButton btnGuardarPedido;
    private javax.swing.JButton btnNuevoProveedor;
    private javax.swing.JComboBox<String> cmbPresentaciones;
    private javax.swing.JComboBox<String> cmbProductos;
    private javax.swing.JComboBox<String> cmbProveedores;
    private javax.swing.JComboBox<String> cmbTipos;
    private com.toedter.calendar.JDateChooser fecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblInfoProducto;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblfondo;
    private javax.swing.JLabel lblinfoNuevoPedido;
    private javax.swing.JLabel lblinfoNumero;
    private javax.swing.JLabel lblinfocategoria;
    private javax.swing.JLabel lblinfoproductos;
    private javax.swing.JLabel lblinfoproveedor;
    private javax.swing.JTable tblProductos;
    // End of variables declaration//GEN-END:variables
}
