package Formularios;

import java.awt.Dimension;
import java.awt.Image;
import javax.swing.ImageIcon;

public class FrmMenuPrincipal extends javax.swing.JFrame {
//codigo para agregar imagenes
    ImageIcon imag = new ImageIcon(getClass().getResource("/iconos/agricortado.png"));
    ImageIcon icon;
    ImageIcon pedido = new ImageIcon(getClass().getResource("/iconos/pedidoscamion.png"));
    ImageIcon ped;
    ImageIcon producto = new ImageIcon(getClass().getResource("/iconos/productosaco.png"));
    ImageIcon prod;
    ImageIcon ventas = new ImageIcon(getClass().getResource("/iconos/Ventasicon.png"));
    ImageIcon vent;
    ImageIcon inventario = new ImageIcon(getClass().getResource("/iconos/inventarioicon.png"));
    ImageIcon  invent;
    ImageIcon fondo = new ImageIcon(getClass().getResource("/iconos/fondo2.jpg"));
    ImageIcon  fond;
    
    //codigo para llamar formularios
    FrmProductos CargarProducto=new FrmProductos();
    FrmPedidos CargarPedido=new FrmPedidos();
    FrmVentas CargarVentas=new FrmVentas();
    FrmInventario CargarInventario= new FrmInventario();
    

    public FrmMenuPrincipal() {
        initComponents();
        //Ajustando imagenes con su etiqueta o boton
        this.setSize(new Dimension(540, 625));
        this.icon = new ImageIcon(imag.getImage().getScaledInstance(lblimagen.getWidth(), lblimagen.getHeight(), Image.SCALE_DEFAULT));
        lblimagen.setIcon(icon);
        this.ped = new ImageIcon(pedido.getImage().getScaledInstance(btnPedidos.getWidth(), btnPedidos.getHeight(), Image.SCALE_DEFAULT));
        btnPedidos.setIcon(ped);
        this.prod = new ImageIcon(producto.getImage().getScaledInstance(btnProductos.getWidth(), btnProductos.getHeight(), Image.SCALE_DEFAULT));
        btnProductos.setIcon(prod);
        this.vent = new ImageIcon(ventas.getImage().getScaledInstance(btnVentas.getWidth(), btnVentas.getHeight(), Image.SCALE_DEFAULT));
        btnVentas.setIcon(vent);
        this.invent = new ImageIcon(inventario.getImage().getScaledInstance(btnInventario.getWidth(), btnInventario.getHeight(), Image.SCALE_DEFAULT));
        btnInventario.setIcon(invent);
        this.fond = new ImageIcon(fondo.getImage().getScaledInstance(lblfondo.getWidth(), lblfondo.getHeight(), Image.SCALE_DEFAULT));
        lblfondo.setIcon(fond);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnProductos = new javax.swing.JButton();
        btnVentas = new javax.swing.JButton();
        lblimagen = new javax.swing.JLabel();
        btnPedidos = new javax.swing.JButton();
        btnInventario = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        lblfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(540, 580));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnProductos.setBackground(new java.awt.Color(225, 251, 173));
        btnProductos.setText("Productos");
        btnProductos.setPreferredSize(new java.awt.Dimension(60, 60));
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });
        getContentPane().add(btnProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 224, 207));

        btnVentas.setBackground(new java.awt.Color(225, 251, 173));
        btnVentas.setText("Ventas");
        btnVentas.setMaximumSize(new java.awt.Dimension(60, 60));
        btnVentas.setMinimumSize(new java.awt.Dimension(60, 60));
        btnVentas.setPreferredSize(new java.awt.Dimension(60, 60));
        btnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasActionPerformed(evt);
            }
        });
        getContentPane().add(btnVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 130, 220, 207));
        getContentPane().add(lblimagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 190, 100));

        btnPedidos.setBackground(new java.awt.Color(225, 251, 173));
        btnPedidos.setText("Pedidos");
        btnPedidos.setMaximumSize(new java.awt.Dimension(60, 60));
        btnPedidos.setMinimumSize(new java.awt.Dimension(60, 60));
        btnPedidos.setPreferredSize(new java.awt.Dimension(60, 60));
        btnPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidosActionPerformed(evt);
            }
        });
        getContentPane().add(btnPedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 218, 207));

        btnInventario.setBackground(new java.awt.Color(225, 251, 173));
        btnInventario.setText("Inventario");
        btnInventario.setMaximumSize(new java.awt.Dimension(60, 60));
        btnInventario.setMinimumSize(new java.awt.Dimension(60, 60));
        btnInventario.setPreferredSize(new java.awt.Dimension(60, 60));
        btnInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 220, 200));

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 90, 30));

        lblfondo.setMaximumSize(new java.awt.Dimension(540, 625));
        lblfondo.setMinimumSize(new java.awt.Dimension(540, 625));
        lblfondo.setPreferredSize(new java.awt.Dimension(540, 625));
        getContentPane().add(lblfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 625));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasActionPerformed
        CargarVentas.show();
    }//GEN-LAST:event_btnVentasActionPerformed

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
       CargarProducto.show();
    }//GEN-LAST:event_btnProductosActionPerformed

    private void btnPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidosActionPerformed
        CargarPedido.show();
    }//GEN-LAST:event_btnPedidosActionPerformed

    private void btnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioActionPerformed
        CargarInventario.show();
    }//GEN-LAST:event_btnInventarioActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
       System.exit(0);
    }//GEN-LAST:event_btnCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnInventario;
    private javax.swing.JButton btnPedidos;
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnVentas;
    private javax.swing.JLabel lblfondo;
    private javax.swing.JLabel lblimagen;
    // End of variables declaration//GEN-END:variables
}
