
package Formularios;

import java.awt.Dimension;
import java.awt.Image;
import javax.swing.ImageIcon;

public class FrmPedidos extends javax.swing.JFrame {
ImageIcon fondo = new ImageIcon(getClass().getResource("/iconos/fondo2.jpg"));
    ImageIcon  fond;
    public FrmPedidos() {
        initComponents();
        this.setSize(new Dimension(540, 625));
        this.fond = new ImageIcon(fondo.getImage().getScaledInstance(lblfondo.getWidth(), lblfondo.getHeight(), Image.SCALE_DEFAULT));
        lblfondo.setIcon(fond);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNuevoPedido = new javax.swing.JButton();
        btnHistorialPedidos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(540, 580));
        setMinimumSize(new java.awt.Dimension(540, 580));
        setName("framePedidos"); // NOI18N
        setPreferredSize(new java.awt.Dimension(540, 580));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNuevoPedido.setText("Agregar pedido");
        getContentPane().add(btnNuevoPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 229, 220));

        btnHistorialPedidos.setText("Historial pedidos");
        getContentPane().add(btnHistorialPedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 237, 220));

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 30)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pedidos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 241, 85));

        lblfondo.setMaximumSize(new java.awt.Dimension(540, 625));
        lblfondo.setMinimumSize(new java.awt.Dimension(540, 625));
        lblfondo.setPreferredSize(new java.awt.Dimension(540, 625));
        getContentPane().add(lblfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 625));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPedidos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHistorialPedidos;
    private javax.swing.JButton btnNuevoPedido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblfondo;
    // End of variables declaration//GEN-END:variables
}
