/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Mi Pc
 */
public class FrmVentas extends javax.swing.JFrame {
ImageIcon fondo = new ImageIcon(getClass().getResource("/iconos/fondo2.jpg"));
    ImageIcon  fond;
    
     FrmNuevaVenta CargarNuevaVenta= new FrmNuevaVenta();
     FrmHistorial CargarHistorial= new FrmHistorial();
    
    
    public FrmVentas() {
        initComponents();
        this.fond = new ImageIcon(fondo.getImage().getScaledInstance(lblfondo.getWidth(), lblfondo.getHeight(), Image.SCALE_DEFAULT));
        lblfondo.setIcon(fond);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVerHistorial = new javax.swing.JButton();
        btnAgregarNuevaVenta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(540, 580));
        setMinimumSize(new java.awt.Dimension(540, 580));
        setPreferredSize(new java.awt.Dimension(540, 580));
        setResizable(false);
        setSize(new java.awt.Dimension(540, 580));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVerHistorial.setText("Ver historial");
        btnVerHistorial.setMaximumSize(new java.awt.Dimension(60, 60));
        btnVerHistorial.setMinimumSize(new java.awt.Dimension(60, 60));
        btnVerHistorial.setPreferredSize(new java.awt.Dimension(60, 60));
        btnVerHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerHistorialActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 170, 170));

        btnAgregarNuevaVenta.setText("Agregar Nueva Venta");
        btnAgregarNuevaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarNuevaVentaActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarNuevaVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 170, 170));

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ventas");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 214, 47));

        lblfondo.setMaximumSize(new java.awt.Dimension(540, 580));
        lblfondo.setMinimumSize(new java.awt.Dimension(540, 580));
        lblfondo.setPreferredSize(new java.awt.Dimension(540, 580));
        getContentPane().add(lblfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 1, 540, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarNuevaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarNuevaVentaActionPerformed
       
        CargarNuevaVenta.show();
        
    }//GEN-LAST:event_btnAgregarNuevaVentaActionPerformed

    private void btnVerHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerHistorialActionPerformed
        CargarHistorial.show();
    }//GEN-LAST:event_btnVerHistorialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmVentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarNuevaVenta;
    private javax.swing.JButton btnVerHistorial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblfondo;
    // End of variables declaration//GEN-END:variables
}
